services:
  valkey:
    image: valkey/valkey:8-alpine
    container_name: ticker_rush_valkey
    command: sh -c "valkey-server --port $$REDIS_PORT"
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    environment:
      - REDIS_PORT
    volumes:
      - valkey_data:/data
    restart: always

  postgres:
    image: postgres:16-alpine
    container_name: ticker_rush_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  exchange:
    build:
      context: .
      dockerfile: container/backend.Dockerfile
      target: exchange-image
    container_name: ticker_rush_exchange
    env_file:
      - .env
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      - REDIS_HOST=valkey
      - POSTGRES_HOST=postgres
    depends_on:
      - valkey
      - postgres
    restart: always

  fetcher:
    build:
      context: .
      dockerfile: container/backend.Dockerfile
      target: fetcher-image
    container_name: ticker_rush_fetcher
    env_file:
      - .env
    environment:
      - REDIS_HOST=valkey
      - POSTGRES_HOST=postgres
    depends_on:
      - valkey
    restart: always

  frontend:
    build:
      context: .
      dockerfile: container/frontend.Dockerfile
    container_name: ticker_rush_frontend
    env_file:
      - .env
    ports:
      - "${CLIENT_PORT}:8080"
    depends_on:
      - exchange
    restart: always
volumes:
  valkey_data:
  postgres_data:
